version: '3'
services:
  app:
    container_name: php-app
    image: myapp
    ports:
      - 1234:80
    volumes:
      - ./app/:/var/www/html/
    depends_on:
    - db
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: passroot
        MYSQL_DATABASE: pizza_data
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
        - 8080:80
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
volumes:
  my-datavolume:
